In [1]:
# Analytics
# 1 Numpy- data store, mathematical and linear algebric functions
# Pandas- data load, preprocees, data cleaning, insights
# Matplotlib- visualization
# Seaborn - Advance visualization and Statistical analysis
# Projects

In [ ]:
import numpy as np

In [ ]:
di=numpy.array([10,20,30])
ti=numpy.array([5,10,15])
sp=di/ti
sp

array([2., 2., 2.])

In [ ]:
a=[1,2,3,4,5]
b=numpy.array(a)
b

array([1, 2, 3, 4, 5])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b=np.array([[3,4,5,6,7]])
b

array([[3, 4, 5, 6, 7]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
di=[10,20,30]
ti=[5,10,15]
# sp=?
print(di/ti)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
di+ti

[10, 20, 30, 5, 10, 15]

Numpy stands for Numerical python. Numpy is the foundational Python library that is widely used for numerical calculations and linear algebra. ndarray and matrix objects are commonly used numpy objects. ndarray objects are created from the numpy ndarray class. matrix objects are created from the numpy matrix class. If you’re new to numpy, you may get confused with numpy ndarray and numpy matrix objects.

In [ ]:
di=numpy.array([10,20,30])
ti=numpy.array([5,10,15])
sp=di/ti
print(sp,type(sp))

[2. 2. 2.] <class 'numpy.ndarray'>


In [ ]:
import numpy

In [ ]:
# List- List are my data type
#        we cant perfrom the mathematical operations in a list
#        list require more memory to store the data
#        Time complexity of list are high

# array- array is a method in a python library numpy
#        We can perform the mathematical operations in the array
#        array require less memory to store the data. thats why we use the array for storing the data
#        Time complexity of are faster


# Propeties of an array
- ndim
- shape
- size
- dtype

In [ ]:
import numpy as np


In [ ]:
a=np.array([1,2,3,4,5])
# print(a)
# print(type(a))
# print(a.ndim)
# print(a.shape)

In [ ]:
b=np.array([[1,2,3,4,5]])
print(b,type(b))
print(b.ndim)
print(b.shape)
print(b.size)

[[1 2 3 4 5]] <class 'numpy.ndarray'>
2
(1, 5)
5


In [ ]:
c=np.array([[1,2,3],[5,6,7],[7,8,9]])
print(c,type(c))
print(c.ndim)
print(c.shape)
print(c.size)

[[1 2 3]
 [5 6 7]
 [7 8 9]] <class 'numpy.ndarray'>
2
(3, 3)
9


In [ ]:
x=np.array([[1],[3],[4]])
print(x.shape)
print(x.size)

(3, 1)
3


In [ ]:
d=np.array([[[[1,2,3],[5,6,7],[7,8,9]]]])
print(d,type(d))
print(d.ndim)
print(d.shape)
print(d.size)

[[[[1 2 3]
   [5 6 7]
   [7 8 9]]]] <class 'numpy.ndarray'>
4
(1, 1, 3, 3)
9


In [ ]:
e=np.array([[[[1,2,3],[5,6,7],[7,8,9],[7,8,9],[1,1,1]]]])
print(e,type(e))
print(e.ndim)
print(e.shape)
print(e.size)

[[[[1 2 3]
   [5 6 7]
   [7 8 9]
   [7 8 9]
   [1 1 1]]]] <class 'numpy.ndarray'>
4
(1, 1, 5, 3)
15


In [ ]:
z=np.array([[[[[2,3],[5,6]]]]])
print(z.ndim)
print(z)
print(z.shape)

5
[[[[[2 3]
    [5 6]]]]]
(1, 1, 1, 2, 2)


In [ ]:
f=np.array([[1,2,3,4,5.2]])
print(f)
print(f.dtype)

[[1.  2.  3.  4.  5.2]]
float64


In [ ]:
f=np.array([[1,2,3,4]])
print(f)
print(f.dtype)

[[1 2 3 4]]
int32


In [ ]:
e=np.array([[[[1,2,3],[5,6,7],[7,8,9],[7,8,9],[1,1,1.2]]]])
print(e)
print(e.dtype)

[[[[1.  2.  3. ]
   [5.  6.  7. ]
   [7.  8.  9. ]
   [7.  8.  9. ]
   [1.  1.  1.2]]]]
float64


In [ ]:
#******* By default my array is in 2-D

In [ ]:
x=np.array([[1,2,3,4,5,6]])
y=np.array([[[1,2,39,4,5,6]]])
z=np.array([[1,2,3],[42,5,6],[7,0,9],[10,11,12]])
a=np.array([[[[[1,2,3,4,5,6,7],[8,9,10,11,12,14,13]]]]])


In [ ]:
print(a.shape)
print(a.size)

(1, 1, 1, 2, 7)
14


In [ ]:
# ndim means no of dimensions
# basicaly it represents the axis of the array
# print(x.ndim)
# print(y.ndim)
# print(z.ndim)
# print(a.ndim)

In [ ]:
# shape tells the rows and columns in a array
# print(x.shape)
print(y.shape)
# print(z.shape)
# print(a.shape)

(1, 1, 6)


In [ ]:
# size tells the total elements in a array
print(x.size)
print(y.size)
print(z.size)
print(a.size)

6
6
12
14


In [ ]:
# Mathematical operations
list1=[2,4,6,8,10]
list2=[1,3,5,7,9]
list1+list2 # concatenation

[2, 4, 6, 8, 10, 1, 3, 5, 7, 9]

In [ ]:
list1=np.array([2,4,6,8,10])
list2=np.array([1,3,5,7,9])
list1+list2  # Operation in the Array occur element wise

array([ 3,  7, 11, 15, 19])

## Indexing and Slicing

In [ ]:
a=np.array([[[1,2,3,4,5,6,-7,8,9]]])
print(a)
# print(a.ndim)
# print(a.shape)
# print(a.size)
# print(a.dtype)

[[[1 2 3 4 5 6 7 8 9]]]


In [ ]:
# print(a[0][0][1])
# print(a[0][0][0])
# print(a[0][0][-3])
# print(a[-1][-1][-3])
print(a[0][-1][3])

4


In [ ]:
# print(a[0][0][-1])

In [ ]:
c=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,3]])
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12  3]]


In [ ]:
# print(c[0])
# print(c[0][0])
# print(c[-1][-2])
# print(c[-1][1])

# print(c[-4][-2])
# print(c[2][-2])


In [ ]:
d=np.array([[[[1,2,3],[4,5,6],[7,8,9],[11,12,3]]]])
print(d)
# print(d.shape)
# print(d.size)


[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [11 12  3]]]]


In [ ]:
# print(d[0][0][0])
print(d[0][0][-1][-3])

11


In [ ]:
import numpy as np
f=np.array([[[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15],[16,17,18,19,20]]]])
print(f)
# print(f.ndim)
# print(f.size)
# print(f.shape)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9  0]
   [11 12 13 14 15]
   [16 17 18 19 20]]]]


In [ ]:
print(f[0][0][1:3,2:4])
# print(f[0][0][0:2,2:4])
# print(f[0][0][1:3,1:3])

[[ 8  9]
 [13 14]]


In [ ]:
# print(f[0][0][-2])
# print(f[-1][0][-4][0])
# print(f[0][0][1])
print(f[0][-1][3][2])

18


In [ ]:
print(f)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9  0]
   [11 12 13 14 15]
   [16 17 18 19 20]]]]


In [ ]:
# print(f[0][0][rows,columns])
# print(f[0][0][1:3,2:4])
# print(f[0][0][1:3,1:4])
# print(f[0][0][-4:-3,-4:-3])
# print(f[-1][-1][-1:,-1:])
# print(f[-1][-1][1:,-1:])
# print(f[-1][-1][-1:,:-1])
# print(f[-1][0][-2:,2:100])
# print(f[0][0][1:4,-4:-1])
# print(f[0][-1][-3:-2,0:4])

### Condition in Array

In [ ]:
marks_of_2students=np.array([[44,56,67,78,89,90],[98,76,54,100,59,90]])


In [ ]:
marks_of_2students

array([[ 44,  56,  67,  78,  89,  90],
       [ 98,  76,  54, 100,  59,  90]])

In [ ]:
passing_marks=60

In [ ]:
marks_of_2students>passing_marks

array([[False, False,  True,  True,  True,  True],
       [ True,  True, False,  True, False,  True]])

In [ ]:
marks_of_2students[marks_of_2students>passing_marks]

array([ 67,  78,  89,  90,  98,  76, 100,  90])

### Mathematical functions

Numpy provides useful mathematical functions called Universal functions. These functions operate element-wise on an array,  producing another array as output.Some of these functions are

In [ ]:
import numpy as np

In [ ]:
## sqrt
a=np.array([1,2,3,4])
a=np.sqrt(a)
a

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
 np.sin(a)

array([0.84147098, 0.98776595, 0.98702664, 0.90929743])

In [ ]:
np.cos(a)

array([ 0.54030231,  0.15594369, -0.16055654])

In [ ]:
# help(math)

In [ ]:
len(dir(np))

601

In [ ]:
# help(np)

## Shape manipulation

In [ ]:
import numpy as np

In [ ]:
x=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
print(x.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(x.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print(x.reshape(1,12))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [ ]:
print(x.reshape(6,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
x.shape

(2, 6)

In [ ]:
print(x.reshape(6,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
print(x.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print(x.reshape(1,12))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [ ]:
print(x.reshape(12,1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [ ]:
print(x.reshape(2,5))

ValueError: cannot reshape array of size 12 into shape (2,5)

## Broadcasting

Numpy uses broadcasting to carry out arithmetic operations between arrays of different shapes. In this method Numpy automatically broadcasts the smaller array over the larger array

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([10,20,30,40,50])
arr2=np.array([60,70,80,90,100])

In [ ]:
arr1*arr2

array([ 600, 1400, 2400, 3600, 5000])

In [ ]:
c=2
arr2*c

array([120, 140, 160, 180, 200])

In [ ]:
m=np.array([[[[1,2,3],[4,5,6]]]])
n=np.array([7,8,9])
# print(m.shape)
# print(n.shape)
print(m)

[[[[1 2 3]
   [4 5 6]]]]


In [ ]:
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [ ]:
# print(y.sum())
y.sum(axis=0)

array([5, 7, 9])

In [ ]:
y.sum(axis=1)

array([ 6, 15])

In [ ]:
import numpy as np
Z=np.array([[100,200,300],[400,500,600],[700,800,900]])
print(Z)
# print(Z.sum(axis=0))# here axis=0 rperestns rows
# print(Z.sum(axis=1))# here axis=0 reperests columns

[[100 200 300]
 [400 500 600]
 [700 800 900]]


In [ ]:
print(Z.sum(axis=0))
print(Z.sum(axis=1))

[1200 1500 1800]
[ 600 1500 2400]


### transpose

In [ ]:
marks=np.array([[44,21,26,67,10,30],[99,23,55,1,78,33]])
print(marks)
print(marks.shape)


[[44 21 26 67 10 30]
 [99 23 55  1 78 33]]
(2, 6)


In [ ]:
marks.T

array([[44, 99],
       [21, 23],
       [26, 55],
       [67,  1],
       [10, 78],
       [30, 33]])

In [ ]:
a=np.array([[[1,2,3],[1,1,1]]])
b=np.array([[1,2,3],[1,1,1]])

In [ ]:
print(a)
print(type(a))

[[[1 2 3]
  [1 1 1]]]
<class 'numpy.ndarray'>


In [ ]:
print(a*b)

[[[1 4 9]
  [1 1 1]]]


In [ ]:
x=np.mat([[1,2,3],[1,1,1]])
x

matrix([[1, 2, 3],
        [1, 1, 1]])

In [ ]:
y=np.mat([[1,2,3],[1,1,1]])
y

matrix([[1, 2, 3],
        [1, 1, 1]])

In [ ]:
x=np.mat([[1,2,3],[1,1,1]])
y=np.mat([[1,2,3],[1,1,1]])
print(x.shape,y.shape)
y=y.T
print(x.shape,y.shape)
print(x*y)

(2, 3) (2, 3)
(2, 3) (3, 2)
[[14  6]
 [ 6  3]]


In [ ]:
print(x*y)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
print(x)
print(type(x))

[[1 2 3]
 [1 1 1]]
<class 'numpy.matrix'>


In [ ]:
marks.T

array([[44, 99],
       [21, 23],
       [26, 55],
       [67,  1],
       [10, 78],
       [30, 33]])

In [ ]:
# print(marks.transpose())
print(marks.T)

[[44 99]
 [21 23]
 [26 55]
 [67  1]
 [10 78]
 [30 33]]


In [ ]:
np.mat([[[1,2,3],[4,5,6]]])

ValueError: matrix must be 2-dimensional

### numpy.fromfunction

In [ ]:
np.fromfunction(lambda i,j:i+j,(2,3)) #By default it form a float type array

array([[0., 1., 2.],
       [1., 2., 3.]])

In [ ]:
np.fromfunction(lambda a,b:a*b,(2,2),dtype=int)

array([[0, 0],
       [0, 1]])

In [ ]:
np.fromfunction(lambda m,n:m-n,(2,2))

array([[ 0., -1.],
       [ 1.,  0.]])

In [ ]:
x=np.fromfunction(lambda x,y:x>y,(2,2))
x

array([[False, False],
       [ True, False]])

In [ ]:
b=np.array(x,ndmin=5)
b

array([[[[[False, False],
          [ True, False]]]]])

In [ ]:
b.ravel()

array([False, False,  True, False])

In [ ]:
print(a)

[[1 2]
 [3 4]]


In [ ]:
print(a)

[[[1 2 3]
  [1 1 1]]]


In [ ]:
np.fromfunction(lambda a,b:a+b,(2,2))

array([[0., 1.],
       [1., 2.]])

### arange and linspace

In [ ]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

In [ ]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,4)

array([1, 5, 9])

In [ ]:
np.linspace(1,10,20)


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
5.26315789-4.78947368

0.47368420999999916

In [ ]:
9.05263158-8.57894737

0.47368421000000005

In [ ]:
1.94736842-1.47368421

0.47368421000000005

In [ ]:
6.21052632-5.73684211

0.47368420999999916

In [ ]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

In [ ]:
np.arange(10,1,-4)

array([10,  6,  2])

In [ ]:
np.arange(2.5,11.5)

array([ 2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [ ]:
np.arange(2,10.9,2.5)

array([2. , 4.5, 7. , 9.5])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(17,2,-3)

array([17, 14, 11,  8,  5])

In [ ]:
print("Numbers spaced apart by 10:",np.arange(50,100,10))

Numbers spaced apart by 10: [50 60 70 80 90]


In [ ]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5))

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [ ]:
print("Numbers in reverse order:",np.arange(100,0,-20))

Numbers in reverse order: [100  80  60  40  20]


In [ ]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [3]:
import numpy as np

In [8]:
np.random.rand(6,4)

array([[-0.67916174,  0.82303335,  0.02561456, -1.45533518],
       [ 1.24109334,  1.21915237, -0.45621344, -2.45369071],
       [ 0.08648489,  0.46714989,  0.00526648,  1.04475505],
       [-0.98659222,  0.70202534, -0.27985581,  0.91406315],
       [ 0.87052015,  2.24337707, -0.91256846, -0.02193384],
       [ 0.6283624 , -2.31521475, -0.07154439, -0.42200648]])

# array creation

In [ ]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
np.zeros((2,7),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [11]:
np.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [12]:
a=np.ones((5,5),dtype=int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
b=np.zeros((3,3),dtype=int)
b[1][1]=9
b

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [14]:
a[1:4,1:4]=b
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
zL=[]
for i in range(25):
    a=int(input('enter a '))
    L.append(a)
print(L)

enter a 1
enter a 1
enter a 1
enter a 1
enter a 1
enter a 1
enter a 0
enter a 0
enter a 0
enter a 1
enter a 1
enter a 0
enter a 9
enter a 0
enter a 1
enter a 1
enter a 0
enter a 0
enter a 0
enter a 1
enter a 1
enter a 1
enter a 1
enter a 1
enter a 1
[1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 9, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1]


In [ ]:
z=np.array(L,ndmin=2)
z

array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 9, 0, 1, 1, 0, 0, 0, 1, 1, 1,
        1, 1, 1]])

In [ ]:
z.reshape(5,5)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

# Random number generation

In [ ]:
import numpy as np


In [ ]:
a=np.random.rand(5)
a

array([0.03724639, 0.78072493, 0.49882024, 0.44972017, 0.26201415])

In [ ]:
x=np.random.randn(99999)
x

array([-1.47604563, -1.56581573,  0.2513704 , ...,  0.71553874,
        0.73503203,  0.43339274])

In [ ]:
np.random.randint(1,7,4)

array([3, 6, 3, 1])

In [ ]:
np.random.randint(100,300,10)

array([160, 175, 174, 168, 106, 112, 117, 168, 149, 117])

In [ ]:
comp=np.random.randint(1,11)
chance =3
while True:
    user=int(input('guess the number '))
    if comp==user:
        print('guessed')
        break
    else:
        print('lost')


In [ ]:
L=['stone','paper','scissor']
chance=int(input('enter chance '))
user_score=0
comp_score=0
while chance!=0:
    comp=np.random.choice(L)
    user=input('enter ')
    if comp==user:
        print('Tie')
    elif comp=='stone':
        if user=='paper':
            print('user wins')
            user_score+=1
        else:
            print('comp wins')
            comp_score+=1

    elif comp=='paer':
        if user=='scissor':
            print('user wins')
            user_score+=1
        else:
            print('comp wins')
            comp_score+=1

    elif comp=='scissor':
        if user=='stone':
            print('user wins')
            user_score+=1
        else:
            print('comp wins')
            comp_score+=1
    chance=chance-1

if comp_score>user_score:
    print('comp wins',comp_score)
elif comp_score==user_score:
    print('Tie')
else:
    print('user wins',user_score)




enter chance 5
enter paper
Tie
enter paper
comp wins
enter stone
enter scissor
enter paper
comp wins
comp wins 2
